# Generated by Django 4.2 on 2024-02-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_proyecto_imagen_remove_servicio_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen1', models.ImageField(null=True, upload_to='nosotros/imagen1/')),
                ('imagen2', models.ImageField(null=True, upload_to='nosotros/imagen2/')),
                ('titulo', models.CharField(max_length=150)),
                ('mision', models.TextField(max_length=580)),
                ('vision', models.TextField(max_length=580)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
