# Generated by Django 4.2 on 2024-02-28 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_nosotros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nosotros',
            new_name='Nosotro',
        ),
    ]
