# Generated by Django 4.2 on 2024-02-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_nosotros_nosotro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nosotro',
        ),
    ]
