# Generated by Django 4.2 on 2024-03-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='enviado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
